channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.0.2
- pip:
  - mlflow==2.17.2
  - cloudpickle==3.0.0
  - lz4==3.1.3
  - numpy==1.26.4
  - psutil==5.9.0
  - scikit-learn==1.4.2
  - scipy==1.14.0
name: mlflow-env
